import Head from "next/head";
import Image from "next/image";
import ImageHeaderMov from "public/images/image-header-mobile.jpg";
import ImageHeaderDes from "public/images/image-header-desktop.jpg";
import { useBreakpoint } from "../hooks/useBreakpoint";

export default function Home() {
  const breakpoint = useBreakpoint();
  const HeaderImage = breakpoint.xl === true ? ImageHeaderDes : ImageHeaderMov;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main className="flex items-center justify-center xl:h-full bg-[#090B1A] p-6 py-20">
        <div className="bg-[#1B1938] flex rounded-lg  flex-col xl:justify-between xl:max-w-[1110px] xl:flex-row-reverse ">
          <div className="relative xl:w-[48%]  ">
            <Image
              src={HeaderImage}
              alt="image"
              className="xs:rounded-t-lg mix-blend-multiply opacity-75 xl:rounded-r-lg relative z-10"
            ></Image>
            <div className="bg-[#ab5cdb]  w-full  h-full absolute top-0"></div>
          </div>
          <div className="flex flex-col xl:w-[52%] items-center xl:text-left justify-center xl:justify-between gap-6  p-8 text-center  text-[#FFFFFF] xl:py-20 xl:pl-20 xl:pr-32 ">
            <h1 className="text-3xl font-[Inter] font-bold xl:text-4xl">
              Get <span className="text-[#AA5CDB] ">insights</span> that help
              your business grow.
            </h1>
            <p className="text-[#FFFFFF]/50 text-lg px-3 xl:px-0 xl:mb-10 xl:pr-4">
              Discover the benefits of data analytics and make better decisions
              regarding revenue, customer experience, and overall efficiency.
            </p>
            <div className="flex flex-col gap-4 xl:flex-row xl:gap-0 xl:justify-between w-full xl:pr-16">
              <div>
                <h1 className="font-[Inter] font-bold text-2xl ">10k+</h1>
                <p className="text-[#FFFFFF]/60 uppercase">companies</p>
              </div>
              <div>
                <h1 className="font-[Inter] font-bold text-2xl">314</h1>
                <p className="text-[#FFFFFF]/60 uppercase">templates</p>
              </div>
              <div>
                <h1 className="font-[Inter] font-bold text-2xl">12M+</h1>
                <p className="text-[#FFFFFF]/60 uppercase">queries</p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
